-- MySQL Script generated by MySQL Workbench
-- qua 14 nov 2018 16:18:27 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema S.I_HorasComplementares
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema S.I_HorasComplementares
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `S.I_HorasComplementares` DEFAULT CHARACTER SET utf8 ;
USE `S.I_HorasComplementares` ;

-- -----------------------------------------------------
-- Table `S.I_HorasComplementares`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S.I_HorasComplementares`.`atividade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(300) NOT NULL,
  `ch_maxima` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S.I_HorasComplementares`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S.I_HorasComplementares`.`grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S.I_HorasComplementares`.`certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S.I_HorasComplementares`.`certificado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ch_total` VARCHAR(7) NOT NULL,
  `data_envio` VARCHAR(20) NOT NULL,
  `local` VARCHAR(60) NOT NULL,
  `ch_validada` VARCHAR(7) NULL,
  `observacao` MEDIUMTEXT NULL,
  `atividade_id` INT NOT NULL,
  `grupo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_certificado_atividade1_idx` (`atividade_id` ASC),
  INDEX `fk_certificado_grupo1_idx` (`grupo_id` ASC),
  CONSTRAINT `fk_certificado_atividade1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `S.I_HorasComplementares`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_certificado_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `S.I_HorasComplementares`.`grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S.I_HorasComplementares`.`coordenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S.I_HorasComplementares`.`coordenador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_coordenador_cadastro_idx` (`cadastro_id` ASC),
  CONSTRAINT `fk_coordenador_cadastro`
    FOREIGN KEY (`cadastro_id`)
    REFERENCES `S.I_HorasComplementares`.`cadastro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S.I_HorasComplementares`.`cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S.I_HorasComplementares`.`cadastro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL COMMENT '	',
  `senha` VARCHAR(45) NOT NULL,
  `data_nascimento` VARCHAR(20) NOT NULL,
  `campus` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `coordenador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cadastro_coordenador1_idx` (`coordenador_id` ASC),
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S.I_HorasComplementares`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S.I_HorasComplementares`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) NOT NULL,
  `cadastro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aluno_cadastro_idx` (`cadastro_id` ASC),
  CONSTRAINT `fk_aluno_cadastro`
    FOREIGN KEY (`cadastro_id`)
    REFERENCES `S.I_HorasComplementares`.`cadastro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `S.I_HorasComplementares`.`certificado_has_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `S.I_HorasComplementares`.`certificado_has_aluno` (
  `certificado_id` INT NOT NULL,
  `aluno_id` INT NOT NULL,
  PRIMARY KEY (`certificado_id`, `aluno_id`),
  INDEX `fk_certificado_has_aluno_aluno1_idx` (`aluno_id` ASC),
  INDEX `fk_certificado_has_aluno_certificado1_idx` (`certificado_id` ASC),
  CONSTRAINT `fk_certificado_has_aluno_certificado1`
    FOREIGN KEY (`certificado_id`)
    REFERENCES `S.I_HorasComplementares`.`certificado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_certificado_has_aluno_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `S.I_HorasComplementares`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
